# deactivate all types of messages generated by Keras 
# 0 = all messages are logged (default behavior)
# 1 = INFO messages are not printed
# 2 = INFO and WARNING messages are not printed
# 3 = INFO, WARNING, and ERROR messages are not printed

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

train_df = pd.read_csv("train_set.csv")
val_df = pd.read_csv("validation_set.csv")
test_df = pd.read_csv("test_set.csv")

cyclical_features = ['day_sin', 'day_cos']

features_to_scale = [
    'temperature_2m_mean',
    'temperature_2m_max',
    'temperature_2m_min', 
    'temp_delta',
    'rolling_mean_3',
    'rolling_mean_7',
]

scaler = StandardScaler()
scaler.fit(train_df[features_to_scale].values)

# Standardize the train, validation and test sets with the calculated statistics
train_scaled = scaler.transform(train_df[features_to_scale].values)
val_scaled   = scaler.transform(val_df[features_to_scale].values)
test_scaled  = scaler.transform(test_df[features_to_scale].values)

train_scaled = np.concatenate([train_scaled, train_df[cyclical_features].values], axis=1)
val_scaled   = np.concatenate([val_scaled, val_df[cyclical_features].values], axis=1)
test_scaled  = np.concatenate([test_scaled, test_df[cyclical_features].values], axis=1)

# Generate input-output sequences for time series forecasting
def create_sequences(data, sequence_length, forecast_horizon):
    xs = []
    ys = []
    for i in range(len(data) - sequence_length - forecast_horizon + 1):
        x = data[i:(i + sequence_length)]
        y = data[(i + sequence_length):(i + sequence_length + forecast_horizon)]
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys)

sequence_length = 15
forecast_horizon = 15
X_train, y_train = create_sequences(train_scaled, sequence_length, forecast_horizon)
X_val, y_val = create_sequences(val_scaled, sequence_length, forecast_horizon)
X_test = test_scaled.reshape(1, sequence_length, test_scaled.shape[1])
y_train = y_train[:, :, 0]  # or change index depending on the target feature
y_val = y_val[:, :, 0]


from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Input, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint

# Training Model Architecture
num_features = train_scaled.shape[1]

model = Sequential()
model.add(Input(shape=(sequence_length, num_features)))
model.add(LSTM(25, return_sequences=True))
model.add(LSTM(25, return_sequences=False))
model.add(Dense(units=forecast_horizon))

# Training process and Hyperparameter settings
optimizer = Adam(learning_rate=0.0005)

model.compile(optimizer=optimizer, loss='mean_absolute_error', metrics=['mae', 'mse'])

checkpoint = ModelCheckpoint('best_model.keras', monitor='val_loss', save_best_only=True)

history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_val, y_val),
          callbacks=[checkpoint], shuffle = False)

# Prediction summary
model = load_model("best_model.keras")

pred_temp = model.predict(X_test)

temp_scaler = StandardScaler()
temp_scaler.fit(train_df["temperature_2m_mean"].values.reshape(-1, 1))
predicted_temperatures = temp_scaler.inverse_transform(pred_temp.reshape(-1, 1))

for i, temp in enumerate(predicted_temperatures.flatten(), start=1):
    print(f"Day {i}: {temp:.2f} °C")

from datetime import date, timedelta

dates = [date.today() + timedelta(days=i+1) for i in range(len(pred_temp.flatten()))]

data = {
    "date": [d.strftime("%Y-%m-%d") for d in dates],
    "predicted_avg_temperature (in °C)": [round(temp, 2) for temp in predicted_temperatures.flatten()]
}

pred_df = pd.DataFrame(data)

# Save to CSV
os.makedirs("../Results", exist_ok=True)
pred_df.to_csv("../Results/predictions.csv", index=False, encoding='utf-8-sig')


import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

# Plot training and validation processes per epoch
fig, axis = plt.subplots(nrows=1,ncols=2, figsize=(20,6))

axis[0].plot(history.epoch, history.history['loss']) 
axis[0].plot(history.epoch, history.history['val_loss']) 
axis[0].set_xlabel("Epochs") 
axis[0].set_ylabel("Value") 
axis[0].legend(["MAE", "Val_MAE"]) 
axis[0].set_title("Training Process - MAE") 

axis[1].plot(history.epoch, history.history['mse'])
axis[1].plot(history.epoch, history.history['val_mse'])
axis[1].set_xlabel("Epochs") 
axis[1].set_ylabel("Value") 
axis[1].legend(["MSE", "Val_MSE"])
axis[1].set_title("Training Process - MSE")

plt.savefig('../Results/training_metrics.png', dpi=300)
plt.show()